// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-J9ZuZ72ddcuYdkt7WrdqKsH5_V3PO8M',
    appId: '1:116229275052:web:8b5b349fd5532ef7284e09',
    messagingSenderId: '116229275052',
    projectId: 'expense-tracker-e3da4',
    authDomain: 'expense-tracker-e3da4.firebaseapp.com',
    storageBucket: 'expense-tracker-e3da4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAautytRp8_qZ2V_2rT5PV8RoW0snhBqUc',
    appId: '1:116229275052:android:8d14a6e70babb402284e09',
    messagingSenderId: '116229275052',
    projectId: 'expense-tracker-e3da4',
    storageBucket: 'expense-tracker-e3da4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqIQL4lr-DNcnF7ITZuWgAZbgPPH6d4aM',
    appId: '1:116229275052:ios:a99bb9b147352749284e09',
    messagingSenderId: '116229275052',
    projectId: 'expense-tracker-e3da4',
    storageBucket: 'expense-tracker-e3da4.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqIQL4lr-DNcnF7ITZuWgAZbgPPH6d4aM',
    appId: '1:116229275052:ios:a99bb9b147352749284e09',
    messagingSenderId: '116229275052',
    projectId: 'expense-tracker-e3da4',
    storageBucket: 'expense-tracker-e3da4.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-J9ZuZ72ddcuYdkt7WrdqKsH5_V3PO8M',
    appId: '1:116229275052:web:1d131f12dfa18d65284e09',
    messagingSenderId: '116229275052',
    projectId: 'expense-tracker-e3da4',
    authDomain: 'expense-tracker-e3da4.firebaseapp.com',
    storageBucket: 'expense-tracker-e3da4.firebasestorage.app',
  );
}
